version: "3.8"
services:
  build:
    build:
      context: .
      dockerfile: Dockerfile-build


  dummy-ven20b:
    build: .docker/dummy-ven20b
    restart: always
    ports:
      - "12100:12100"
    depends_on:
      - "build"
    networks:
      xmpp:
      http:
        aliases:
          - ven3.oadr.com


networks:
  http:
  xmpp:

