# SSL configuration
server.ssl.enabled=true
server.ssl.client-auth=want
server.ssl.key-store=cert/Eonti_keystore_ven_111111111111.jks
server.ssl.key-store-password=password
server.ssl.key-alias=111111111111_rsa
server.ssl.key-store-type=JKS
server.ssl.trust-store=cert/truststore.jks
server.ssl.trust-store-password=password

# security logging level configuration
#logging.level.org.springframework.security: DEBUG
# exclude Spring Boot's default security configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.application.name=venServer
server.servlet.context-path=/
server.port=12100

# VTN configuration
oadr.vtn.ven3_httppush.server.port=12100
oadr.vtn.ven3_httppush.venUrl=https://ven3.oadr.com:12100
oadr.vtn.ven3_httppush.venid.file=cert/ven3.oadr.com.fingerprint

oadr.vtn.ven3_httppush.vtnid.file=cert/vtn.oadr.com-rsa.fingerprint
oadr.vtn.ven3_httppush.vtnUrl=https://vtn.oadr.com:8181/
oadr.vtn.ven3_httppush.venName=ven3.oadr.com
# Test xml file path for VEN dataSource. The report data should be got through the API of VEN3_HTTPUSH under production environment.
oadr.vtn.ven3_httppush.filePath=DummyVEN20b/src/main/resources/
# VEN report dataSource for VEN3_HTTPUSH
oadr.vtn.ven3_httppush.venReportDataSource=https://ven3.oadr.com:12100/OpenADR2/2.0b/VEN/data/getBusinessData
# VEN model config
oadr.pullFrequencySeconds=5
oadr.reportOnly=false
oadr.xmlSignature=false
oadr.pullModel=false
oadr.security.validateOadrPayloadAgainstXsdFilePath=false
oadr.security.replayProtectAcceptedDelaySecond=1200
# the X.509 client certificate CN field disabled(Only for testing purposes)
oadr.security.CN_disabled=true

# OpenADR Certificate configuration FOR VEN3_HTTPUSH - Now using dynamic keys based on vtnConfigName
oadr.vtn.ven3_httppush.security.use_jks_extraction=true
oadr.vtn.ven3_httppush.security.keystore.path=cert/Eonti_keystore_ven_111111111111.jks
oadr.vtn.ven3_httppush.security.keystore.password=password
oadr.vtn.ven3_httppush.security.keystore.type=JKS
oadr.vtn.ven3_httppush.security.truststore.path=cert/truststore.jks
oadr.vtn.ven3_httppush.security.truststore.password=password

